/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Cliente;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import classes.Validacoes;

/**
 *
 * @author 144fps
 */
public class CadastroCliente extends javax.swing.JFrame {
    static ArrayList<Cliente> clientes;
    static Cliente clienteAtual;
    

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        this.clientes = new ArrayList<Cliente>();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadosCliente = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        cpfTextField = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        lblDataDeNascimento = new javax.swing.JLabel();
        btnEntrarCadastrar = new javax.swing.JButton();
        dataDeNascimentoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/sanduiche.png")).getImage());
        setResizable(false);

        pnlDadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Dados do cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        pnlDadosCliente.setName(""); // NOI18N

        lblCpf.setText("CPF:");

        cpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextFieldActionPerformed(evt);
            }
        });

        lblNome.setText("NOME:");

        lblDataDeNascimento.setText("DATA DE NASCIMENTO:");

        btnEntrarCadastrar.setText("Entrar / Cadastrar");
        btnEntrarCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarCadastrarActionPerformed(evt);
            }
        });

        dataDeNascimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeNascimentoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosClienteLayout = new javax.swing.GroupLayout(pnlDadosCliente);
        pnlDadosCliente.setLayout(pnlDadosClienteLayout);
        pnlDadosClienteLayout.setHorizontalGroup(
            pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                        .addComponent(lblCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                        .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                        .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(btnEntrarCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                                .addComponent(lblDataDeNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataDeNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGap(12, 12, 12)))
                .addGap(142, 142, 142))
        );
        pnlDadosClienteLayout.setVerticalGroup(
            pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDeNascimento)
                    .addComponent(dataDeNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnEntrarCadastrar)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(pnlDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_cpfTextFieldActionPerformed

    private void btnEntrarCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarCadastrarActionPerformed
		String cpf = this.cpfTextField.getText();
		String name = this.nameTextField.getText();
		String dataDeNascimento = this.dataDeNascimentoTextField.getText();

		if (Validacoes.isEmpty(name) || Validacoes.isEmpty(cpf) || Validacoes.isEmpty(dataDeNascimento)) {
			JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Erro", JOptionPane.PLAIN_MESSAGE);
			return;
		}

		if (!Validacoes.isCPF(cpf)) {
			JOptionPane.showMessageDialog(null, "Por favor, digite o CPF no seguinte formato: 000.000.000-00.", "Erro", JOptionPane.PLAIN_MESSAGE);
			return;
		}

		if (!Validacoes.isData(dataDeNascimento)) {
			JOptionPane.showMessageDialog(null, "Por favor, digite uma data valida.", "Erro", JOptionPane.PLAIN_MESSAGE);
			return;
		}

		if (clienteExiste(cpf, clientes)) {
			clienteAtual = encontrarCliente(cpf, clientes);
		} else {
			clienteAtual = new Cliente(cpf, name, dataDeNascimento);
			clientes.add(clienteAtual);
		}

		// Proxima pagina
		FazerPedido telaFazerPedido = new FazerPedido();
		telaFazerPedido.setVisible(true);
		this.setVisible(false);
    }//GEN-LAST:event_btnEntrarCadastrarActionPerformed

    private void dataDeNascimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeNascimentoTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_dataDeNascimentoTextFieldActionPerformed

	private Cliente encontrarCliente(String cpf, ArrayList<Cliente> clientes) {
		for (Cliente cliente : clientes) {
			if (cliente.getCpf() == cpf) {
				return cliente;
			}
		}
		return null;
	}

	private boolean clienteExiste(String cpf, ArrayList<Cliente> clientes) {
		for (Cliente cliente : clientes) {
			if (cliente.getCpf() == cpf) {
				return true;
			}
		}
		return false;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CadastroCliente().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarCadastrar;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JTextField dataDeNascimentoTextField;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataDeNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel pnlDadosCliente;
    // End of variables declaration//GEN-END:variables
}
