/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Caixa;
import classes.Cozinheiro;
import classes.Funcionario;
import classes.Ingrediente;
import classes.Pedido;
import classes.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static telas.TelaInicial.Ingredientes;
import static telas.TelaInicial.ProdutosDisponiveis;
import static telas.TelaInicial.listaPedidos;

/**
 *
 * @author 144fps
 */
public class CozinheiroeCaixa extends javax.swing.JFrame {
    public static ArrayList<Funcionario> listaFuncionario;

    /**
     * Creates new form CozinheiroeCaixa
     */
    public CozinheiroeCaixa() {
        listaFuncionario = new ArrayList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCozinheiro = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Selecione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        btnCozinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cozinheiro.png"))); // NOI18N
        btnCozinheiro.setText("Cozinheiro");
        btnCozinheiro.setToolTipText("Acessar painel cozinheiro");
        btnCozinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCozinheiroActionPerformed(evt);
            }
        });

        btnCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa.png"))); // NOI18N
        btnCaixa.setText("Caixa");
        btnCaixa.setToolTipText("Acessar painel caixa");
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnCozinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCozinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        btnSair.setText("Sair");
        btnSair.setToolTipText("fechar janela");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSair)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        //if(listaFuncionario.size() == 0){
            //JOptionPane.showMessageDialog(null,"Nenhum funcionário cadastrado ainda!","Mensagem",JOptionPane.PLAIN_MESSAGE);
        //}else{    
            boolean achou = false;
            //String senha = JOptionPane.showInputDialog("Informe sua senha de funcionário:");
            String senha = "arthur";
            Ingrediente in = new Ingrediente("Pão", 2);
            Ingredientes.add(in);
            Produto pro = new Produto(500, "hamburguer", Ingredientes);
            ProdutosDisponiveis.add(pro);
            Pedido p = new Pedido(ProdutosDisponiveis, "dinheiro", 500, true, 12321, true, true);
            listaPedidos.add(p);
            Caixa cai = new Caixa(listaPedidos,"arthur", 10, 1111, "jj", "20/10/2021");
            listaFuncionario.add(cai);
            if(listaPedidos.size() != 0){
            for(int i = 0; i<listaFuncionario.size();i++){
                 if(listaFuncionario.get(i) instanceof Caixa){
                     Caixa c = (Caixa)listaFuncionario.get(i);
                     if(senha.equals(c.getSenha())){
                         new PedidosEmDinheiro().setVisible(true);
                         achou = true;

                     }

                 }
                 }
            if(!achou){
                JOptionPane.showMessageDialog(null,"A senha informada não corresponde a um caixa!","Mensagem",JOptionPane.PLAIN_MESSAGE);
            }
            }else{
                JOptionPane.showMessageDialog(null,"A lista de pedidos ainda está vazia!","Mensagem",JOptionPane.PLAIN_MESSAGE);
            }
        //}
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCozinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCozinheiroActionPerformed
        if(listaFuncionario.size() == 0){
            JOptionPane.showMessageDialog(null,"Nenhum funcionário cadastrado ainda!","Mensagem",JOptionPane.PLAIN_MESSAGE);
        }else{    
            boolean achou = false;
            //String senha = JOptionPane.showInputDialog("Informe sua senha de funcionário:");
            String senha = "arthur";
            Ingrediente in = new Ingrediente("Pão", 2);
            Ingredientes.add(in);
            Produto pro = new Produto(500, "hamburguer", Ingredientes);
            ProdutosDisponiveis.add(pro);
            Pedido p = new Pedido(ProdutosDisponiveis, "cartão", 500, true, 12321, true, true);
            listaPedidos.add(p);
            Cozinheiro coz = new Cozinheiro(listaPedidos,"arthur", 10, 1111, "jj", "20/10/2021");
            listaFuncionario.add(coz);
            if(listaPedidos.size() != 0){
            for(int i = 0; i<listaFuncionario.size();i++){
                 if(listaFuncionario.get(i) instanceof Cozinheiro){
                     Cozinheiro c = (Cozinheiro)listaFuncionario.get(i);
                     if(senha.equals(c.getSenha())){
                         new ListaDePedidos().setVisible(true);
                         achou = true;

                     }

                 }
                 }
            if(!achou){
                JOptionPane.showMessageDialog(null,"A senha informada não corresponde a um cozinheiro!","Mensagem",JOptionPane.PLAIN_MESSAGE);
            }
            }else{
                JOptionPane.showMessageDialog(null,"A lista de pedidos ainda está vazia!","Mensagem",JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCozinheiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CozinheiroeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CozinheiroeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CozinheiroeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CozinheiroeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CozinheiroeCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnCozinheiro;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
