/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Funcionario;
import classes.Pedido;
import classes.Produto;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author Marcelo Piano
 */
public class TelaInicial extends javax.swing.JFrame {

	static ArrayList<Pedido> listaPedidos;
	static ArrayList<Produto> ProdutosDisponiveis;
	static ArrayList<Funcionario> ListaFuncionario;
	private Calendar calendario;

	/**
	 * Creates new form TelaInicial
	 */
	public TelaInicial() {
		initComponents();
		listaPedidos = new ArrayList();
		ProdutosDisponiveis = new ArrayList();
		ListaFuncionario = new ArrayList();
		setLocationRelativeTo(null);
		Calendar c = Calendar.getInstance();

		// 
		lblDataTelaInicial.setText(String.valueOf(c.get(Calendar.DAY_OF_MONTH)) + "/"
				+ String.valueOf(c.get(Calendar.MONTH) + 1) + "/"
				+ String.valueOf(c.get(Calendar.YEAR)));

	}

	/**
	 * This method is called from within the constructor to initialize
	 * the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCliente = new javax.swing.JButton();
        lblInterfaceTelaInicial = new javax.swing.JLabel();
        lblEscolhaPerfilTelainicial = new javax.swing.JLabel();
        sprTelaInicial = new javax.swing.JSeparator();
        btnGerenteTelaInicial = new javax.swing.JButton();
        btnFuncionarioTelaInicial = new javax.swing.JButton();
        lblDataTelaInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        lblInterfaceTelaInicial.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblInterfaceTelaInicial.setText("Interface TechBurguer");

        lblEscolhaPerfilTelainicial.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblEscolhaPerfilTelainicial.setText("Escolha o Perfil desse despositivo:");

        btnGerenteTelaInicial.setText("Gerente");
        btnGerenteTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenteTelaInicialActionPerformed(evt);
            }
        });

        btnFuncionarioTelaInicial.setText("Funcionário");
        btnFuncionarioTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioTelaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sprTelaInicial, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(lblEscolhaPerfilTelainicial)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGerenteTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFuncionarioTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(213, 213, 213))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblInterfaceTelaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDataTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterfaceTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sprTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEscolhaPerfilTelainicial)
                .addGap(18, 18, 18)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFuncionarioTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnGerenteTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed

		CadastroCliente telaCliente = new CadastroCliente();
		telaCliente.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnGerenteTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenteTelaInicialActionPerformed
		// TODO add your handling code here:

		new LoginGerente().setVisible(true);
    }//GEN-LAST:event_btnGerenteTelaInicialActionPerformed

    private void btnFuncionarioTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioTelaInicialActionPerformed
		// TODO add your handling code here:
		new CozinheiroeCaixa().setVisible(true);
    }//GEN-LAST:event_btnFuncionarioTelaInicialActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaInicial().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnFuncionarioTelaInicial;
    private javax.swing.JButton btnGerenteTelaInicial;
    private javax.swing.JLabel lblDataTelaInicial;
    private javax.swing.JLabel lblEscolhaPerfilTelainicial;
    private javax.swing.JLabel lblInterfaceTelaInicial;
    private javax.swing.JSeparator sprTelaInicial;
    // End of variables declaration//GEN-END:variables
}
